version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Addis_Ababa
    open-pull-requests-limit: 10
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /studio
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Africa/Addis_Ababa
    open-pull-requests-limit: 10
    groups:
      studio-minor-and-patch:
        update-types:
          - minor
          - patch
