import {defineField, defineType} from 'sanity'

export const researchSubmissionType = defineType({
  name: 'researchSubmission',
  title: 'Research Submission',
  type: 'document',
  groups: [
    {name: 'review', title: 'Editorial review', default: true},
    {name: 'author', title: 'Author'},
    {name: 'research', title: 'Research'},
    {name: 'files', title: 'File and disclosures'},
  ],
  fields: [
    defineField({name: 'reference', title: 'Submission reference', type: 'string', group: 'review', readOnly: true}),
    defineField({
      name: 'status',
      title: 'Editorial status',
      type: 'string',
      group: 'review',
      initialValue: 'new',
      options: {
        list: [
          {title: 'New', value: 'new'},
          {title: 'In screening', value: 'screening'},
          {title: 'In review', value: 'review'},
          {title: 'Revisions requested', value: 'revisions'},
          {title: 'Accepted', value: 'accepted'},
          {title: 'Declined', value: 'declined'},
        ],
        layout: 'radio',
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'submittedAt',
      title: 'Submitted at',
      type: 'datetime',
      group: 'review',
      readOnly: true,
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'editorialNotes', title: 'Private editorial notes', type: 'text', rows: 5, group: 'review'}),
    defineField({
      name: 'fullName',
      title: 'Corresponding author',
      type: 'string',
      group: 'author',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'author',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'organization',
      title: 'Institution or organization',
      type: 'string',
      group: 'author',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'country',
      title: 'Country or region',
      type: 'string',
      group: 'author',
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'coAuthors', title: 'Co-authors', type: 'text', rows: 5, group: 'author'}),
    defineField({
      name: 'manuscriptTitle',
      title: 'Manuscript title',
      type: 'string',
      group: 'research',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'topic',
      title: 'Primary topic',
      type: 'string',
      group: 'research',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'manuscriptType',
      title: 'Manuscript type',
      type: 'string',
      group: 'research',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'abstract',
      title: 'Abstract',
      type: 'text',
      rows: 10,
      group: 'research',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'keywords',
      title: 'Keywords',
      type: 'string',
      group: 'research',
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'methodology', title: 'Methodology or data sources', type: 'text', rows: 5, group: 'research'}),
    defineField({
      name: 'manuscript',
      title: 'Manuscript file',
      type: 'file',
      group: 'files',
      options: {accept: '.pdf,.doc,.docx'},
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'funding', title: 'Funding or support', type: 'text', rows: 4, group: 'files'}),
    defineField({name: 'conflicts', title: 'Conflicts of interest', type: 'text', rows: 4, group: 'files'}),
    defineField({name: 'coverNote', title: 'Note to editorial team', type: 'text', rows: 5, group: 'files'}),
    defineField({
      name: 'originalityConfirmed',
      title: 'Originality confirmed',
      type: 'boolean',
      group: 'files',
      readOnly: true,
    }),
    defineField({
      name: 'reviewConsent',
      title: 'Storage and review consent',
      type: 'boolean',
      group: 'files',
      readOnly: true,
    }),
  ],
  orderings: [
    {
      title: 'Newest first',
      name: 'submittedAtDesc',
      by: [{field: 'submittedAt', direction: 'desc'}],
    },
  ],
  preview: {
    select: {
      title: 'manuscriptTitle',
      author: 'fullName',
      status: 'status',
      reference: 'reference',
    },
    prepare({title, author, status, reference}) {
      return {
        title: title || 'Untitled submission',
        subtitle: `${reference || 'No reference'} · ${author || 'Unknown author'} · ${status || 'new'}`,
      }
    },
  },
})
